import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Layout/Header";
import { AuthProvider } from "@/contexts/AuthContext";
const poppins = Poppins({
  weight: ["300", "400", "500", "600"],
  subsets: ["devanagari"],
});

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <AuthProvider>
          <Header />
          <main className="max-w-6xl mx-auto mt-5 px-5">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
